import _ from 'lodash';

const projects = [
  'portfolio',
  'awesome-deno-es',
  'wishlisted',
  'wishlisted-backend',
  'Turing-s-Food',
  'watermelon',
  'eterna-cloud',
  'mauriciochavez.dev',
  'my-gatsby-blog',
  'vue-video-browser',
  'denosaurs',
  'deno-rock-paper-scissors',
  'pokelixir',
  'deno-test-action',
  'snake',
  'instadowloader-elixir',
  'black-sheep',
  'identicon-elixir',
  'cards-elixir',
  'openpyxl-image-loader',
  'xylophone-flutter',
  'thehappyghost',
  'random_js_library',
  'un_pesito_app',
  'apis_app_flutter',
  'rick_and_morty_flutter',
  'django_tacos_ecommerce',
  'node-pokedex',
  'queens_puzzle_solver',
  'flutter-rock-paper-scissors',
  'twister_project',
  'thefacebook',
  'express-jinja',
  'superheroes-graphql-api',
  'bottle-of-revolution',
  'recipe-app-api',
  'BillSplitter',
  'BurgerBuilder',
  'FlutterTechStack',
  'rock-paper-scissors',
  'AjedrezJava',
  'ED-Practicas',
  'PyPlayer',
  'PyChat',
  'ICC-Practicas',
];

export default function getRandomProject() {
  return _.shuffle(projects)[0];
}
